#!/bin/bash

# Revisited and fixed by Dj_Dexter 2013-09-24
# re tested in slackware 14.0 and runs fine :)
# only works for wep encripted connections

# die with honor
function usage() {
	echo "usage: ./connectWifi \"<essid>\" [key] [Interface]"
	echo "       *key in ascii prefaces s:[key]"
	echo "Channel number of channel"
        echo "Example connectWifi "essid" s:key 3 wlan1"
	exit 1
}

# killed in disgrace
function die() {
	echo
	echo "   [*] ERROR: $1..."
	echo
	exit 1
}

# check for essid
if [[ $1 ]]; then
	# setup
        pkill dhclient
	echo "Starting..."
	ifconfig $4 down
	dhclient -r $4 -q
        #pkill dhclient
	echo " -Previous connection dropped."
	iwconfig $4 essid "$1"
	echo " -ESSID Set to $1."
	# check for key
	if [[ $2 ]]; then
		iwconfig $4 key $2
		echo " -Key set to $2."
	fi
	# connect
        iwconfig $4 channel "$3"
        ifconfig $4 up
        iwconfig $4 mode Managed
	echo " -Connecting..."
	echo
	dhclient $4
	# announce success
	if [[ $? -eq 0 ]]; then
		echo
		echo "Successfully connected to $1!"
		echo
		exit 0
	fi

else
	# no variables
	usage
fi

# declare failure
die "Failed to connect to $1."