#!/bin/sh
echo "Limpiando paquetes huerfanos"
apt-get autoremove 
apt-get --purge remove `deborphan` 
echo "Limpiando configuraciones de paquetes"
dpkg --purge `COLUMNS=300 dpkg -l | egrep "^rc" | cut -d' ' -f3` 
echo "¡Listo!"