#!/bin/sh
echo "poniendo valores wifi optimos pa no caerse...."
#wtf power in wlan0 = kernel panics =_=
iwconfig wlan0 power off &
iwconfig wlan0 retry 30 &
echo "Activando modo attentionwhere hacia la ap..."
iwconfig wlan0 rts 1
#iwconfig wlan0 rts 512 &
iwconfig wlan0 frag 256 &
echo "terminado :3"
